### ISSUE TITLE
App crashing when cancel is clicked in the dialog

### ISSUE THREAD

**Issue by aman-anand** [jrvansuita/PickImage#69]
`java.lang.NullPointerException: Attempt to invoke interface method 'void com.vansuita.pickimage.listeners.IPickCancel.onCancelClick()' on a null object reference
        at com.vansuita.pickimage.dialog.PickImageBaseDialog$1.onClick(PickImageBaseDialog.java:163)
        at android.view.View.performClick(View.java:5612)
        at android.view.View$PerformClick.run(View.java:22285)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
`

**Comment by BourgoisMickael** [comment]
Same error for me

**Comment by BourgoisMickael** [comment]
it has been fixed i think, i don't have the problem anymore without doing anything

**Comment by tech4lifeapps** [comment]
No, this is a serious bug. So serious that, if not fixed, rests the code useless.

**Comment by saurabhvadhva** [comment]
Same error for me.
