### ISSUE TITLE
setvideo(true) not working

### ISSUE THREAD

**Issue by AmineNac** [jrvansuita/PickImage#70]
After recording a video from the camera, the << pickResult.getPath() >> method returns this value 
 /*/MyCasa/20180420_134658.jpg. it's a JPG !!

**Comment by smail2133** [comment]
The same issue, seems problem need solve by self!

**Comment by DmitriyYakovlev** [comment]
Do you have any suggestions on when this will be fixed?

**Comment by DmitriyYakovlev** [comment]
Note that, the problem is related to file extension only. There is workable video. I have tried to rename file manually and set .mp4 extension. File was fixed

**Comment by SD-LeadDeveloper** [comment]
> Hey there, I think this pull request will solve the problems
> #97

Good Day, I am still experiencing this on 2.2.4 is there any way to fix it?

Kind Regards

**Comment by Joecorleone** [comment]
I am also experiencing the same problem with 
    implementation 'com.github.jrvansuita:PickImage:2.2.4'
    implementation 'com.github.jrvansuita:PickImage:+'
Here is the merge, which should have fixed the problem:

 v2.1.0
Merge pull request #97 from molaeiali/master
Fix problems with video selection
on Oct 1, 2018 7a764d7 zip tar.gz 
>The resulting version is v2.1.0. (note the "v" added)

I tried to use exactly that version
    implementation 'com.github.jrvansuita:PickImage:v2.1.0'
but it does not contain neither the Module IPickCancel nor PickSetup().setVideo(true).

What is the solution?
